name: 'YAML Variables Extractor'
description: 'Extracts variables from a YAML file and sets them as environment variables with a prefix'
author: 'Francisco Nascimento'

runs:
  using: 'docker'
  image: 'Dockerfile'

inputs:
  yaml_file:
    description: 'The path to the YAML file (.yaml or .yml)'
    required: true
  prefix:
    description: 'Prefix for the environment variables (default: YAML_)'
    required: false
    default: 'YAML_'

branding:
  icon: 'file-plus'
  color: 'green'